name: CICD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# Set docker image names.
    - name: Setup env variables
      run: |
        echo "DOCKER_SERVICE=kvalitetsit/kithugs-jonas" >> $GITHUB_ENV
        echo "DOCKER_DOCUMENTATION=kvalitetsit/kithugs-jonas-documentation" >> $GITHUB_ENV

# Checkout source code
    - uses: actions/checkout@v3

# Fail if DOCKER_SERVICE is kithugs-jonas and repo is not kithugs-jonas. This step can be deleted once
    - name: Initial build
      run: ./build/failOnFirstBuild.sh

# Cache maven stuff
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

# if below step is skipped this build is a tag build. Can be used for skipping other steps.
    - name: Is Tag Build
      id: tag
      if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

# Login to docker hub using secrets in GitHub.
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and test
      run: ./build/build.sh
